version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nestjs_api
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT:-3000}:3000"
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - main_public

networks:
  main_public:
    external: true
